packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint-react/eslint-plugin': ^1.52.3
  '@eslint/js': ^9.32.0
  '@hookform/resolvers': ^5.2.1
  '@oslojs/crypto': ^1.0.1
  '@oslojs/encoding': ^1.1.0
  '@radix-ui/react-accordion': ^1.2.11
  '@radix-ui/react-alert-dialog': ^1.1.14
  '@radix-ui/react-aspect-ratio': ^1.1.7
  '@radix-ui/react-avatar': ^1.1.10
  '@radix-ui/react-checkbox': ^1.3.2
  '@radix-ui/react-collapsible': ^1.1.11
  '@radix-ui/react-context-menu': ^2.2.15
  '@radix-ui/react-dialog': ^1.1.14
  '@radix-ui/react-dropdown-menu': ^2.1.15
  '@radix-ui/react-hover-card': ^1.1.14
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-menubar': ^1.1.15
  '@radix-ui/react-navigation-menu': ^1.2.13
  '@radix-ui/react-popover': ^1.1.14
  '@radix-ui/react-progress': ^1.1.7
  '@radix-ui/react-radio-group': ^1.3.7
  '@radix-ui/react-scroll-area': ^1.2.9
  '@radix-ui/react-select': ^2.2.5
  '@radix-ui/react-separator': ^1.1.7
  '@radix-ui/react-slider': ^1.3.5
  '@radix-ui/react-slot': ^1.2.3
  '@radix-ui/react-switch': ^1.2.5
  '@radix-ui/react-tabs': ^1.1.12
  '@radix-ui/react-toggle': ^1.1.9
  '@radix-ui/react-toggle-group': ^1.1.10
  '@radix-ui/react-tooltip': ^1.2.7
  '@tailwindcss/vite': ^4.1.11
  '@tanstack/eslint-plugin-query': ^5.81.2
  '@tanstack/eslint-plugin-router': ^1.129.7
  '@tanstack/react-query': ^5.83.0
  '@tanstack/react-query-devtools': ^5.83.0
  '@tanstack/react-router': ^1.130.2
  '@tanstack/react-router-devtools': ^1.130.2
  '@tanstack/react-router-with-query': ^1.130.2
  '@tanstack/react-start': ^1.130.3
  '@types/node': ^24.1.0
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  '@vitejs/plugin-react': ^4.7.0
  arctic: ^3.7.0
  babel-plugin-react-compiler: latest
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.4
  embla-carousel-react: ^8.6.0
  eslint: ^9.32.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react-hooks: rc
  eslint-plugin-turbo: ^2.5.5
  husky: ^9.1.7
  input-otp: ^1.4.2
  jose: ^6.0.12
  lint-staged: ^16.1.2
  lucide-react: latest
  nanoid: ^5.1.5
  postgres: ^3.4.7
  prettier: ^3.6.2
  prettier-plugin-organize-imports: ^4.2.0
  prettier-plugin-tailwindcss: ^0.6.14
  react: ^19.1.1
  react-day-picker: ^9.8.1
  react-dom: ^19.1.1
  react-hook-form: ^7.61.1
  react-resizable-panels: ^3.0.3
  recharts: ^3.1.0
  sonner: ^2.0.6
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  turbo: ^2.5.5
  tw-animate-css: ^1.3.6
  typescript: ^5.8.3
  typescript-eslint: ^8.38.0
  vaul: ^1.1.2
  vite: ^7.0.6
  vite-tsconfig-paths: ^5.1.4
  zod: ^4.0.13

catalogMode: prefer
