packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@base-ui/react': ^1.1.0
  '@eslint-react/eslint-plugin': ^2.7.2
  '@eslint/js': ^9.39.2
  '@polar-sh/sdk': ^0.42.2
  '@react-email/components': ^1.0.6
  '@react-email/preview-server': ^5.2.5
  '@remixicon/react': ^4.8.0
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/devtools-vite': ^0.4.1
  '@tanstack/eslint-plugin-query': ^5.91.3
  '@tanstack/eslint-plugin-router': ^1.154.7
  '@tanstack/react-devtools': ^0.9.2
  '@tanstack/react-form-devtools': ^0.2.12
  '@tanstack/react-form-start': ^1.27.7
  '@tanstack/react-query': ^5.90.19
  '@tanstack/react-query-devtools': ^5.91.2
  '@tanstack/react-router': ^1.154.12
  '@tanstack/react-router-devtools': ^1.154.12
  '@tanstack/react-router-ssr-query': ^1.154.12
  '@tanstack/react-start': ^1.154.12
  '@types/node': ^25.0.10
  '@types/react': ^19.2.9
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  babel-plugin-react-compiler: ^1.0.0
  better-auth: ^1.4.17
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  date-fns: ^4.1.0
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-turbo: ^2.7.5
  husky: ^9.1.7
  lint-staged: ^16.2.7
  motion: ^12.29.0
  nitro: npm:nitro-nightly@latest
  postgres: ^3.4.8
  prettier: ^3.8.1
  prettier-plugin-organize-imports: ^4.3.0
  prettier-plugin-tailwindcss: ^0.7.2
  react: ^19.2.3
  react-dom: ^19.2.3
  react-email: ^5.2.5
  resend: ^6.8.0
  shadcn: ^3.7.0
  sonner: ^2.0.7
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  turbo: ^2.7.5
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  typescript-eslint: ^8.53.1
  vite: ^8.0.0-beta.9
  zod: ^4.3.6

catalogMode: prefer

overrides:
  vite: ^8.0.0-beta.9
