packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint-react/eslint-plugin': ^2.2.3
  '@eslint/js': ^9.38.0
  '@orpc/client': ^1.10.1
  '@orpc/server': ^1.10.1
  '@orpc/tanstack-query': ^1.10.1
  '@oslojs/crypto': ^1.0.1
  '@oslojs/encoding': ^1.1.0
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-aspect-ratio': ^1.1.7
  '@radix-ui/react-avatar': ^1.1.10
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-context-menu': ^2.2.16
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-hover-card': ^1.1.15
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-menubar': ^1.1.16
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.7
  '@radix-ui/react-radio-group': ^1.3.8
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.7
  '@radix-ui/react-slider': ^1.3.6
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-toggle': 1.1.10
  '@radix-ui/react-toggle-group': 1.1.11
  '@radix-ui/react-tooltip': ^1.2.8
  '@tailwindcss/vite': ^4.1.16
  '@tanstack/devtools-vite': ^0.3.10
  '@tanstack/eslint-plugin-query': ^5.91.2
  '@tanstack/eslint-plugin-router': ^1.133.19
  '@tanstack/react-devtools': ^0.7.8
  '@tanstack/react-form': ^1.23.8
  '@tanstack/react-form-devtools': ^0.1.8
  '@tanstack/react-query': ^5.90.5
  '@tanstack/react-query-devtools': ^5.90.2
  '@tanstack/react-router': ^1.133.27
  '@tanstack/react-router-devtools': ^1.133.27
  '@tanstack/react-router-ssr-query': ^1.133.27
  '@tanstack/react-start': ^1.133.27
  '@types/node': ^24.9.1
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@vitejs/plugin-react': ^5.1.0
  arctic: ^3.7.0
  babel-plugin-react-compiler: ^1.0.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.7
  embla-carousel-react: ^8.6.0
  eslint: ^9.38.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-turbo: ^2.5.8
  husky: ^9.1.7
  input-otp: ^1.4.2
  jose: ^6.1.0
  lint-staged: ^16.2.6
  lucide-react: ^0.548.0
  nanoid: ^5.1.6
  postgres: ^3.4.7
  prettier: ^3.6.2
  prettier-plugin-organize-imports: ^4.3.0
  prettier-plugin-tailwindcss: ^0.7.1
  react: ^19.2.0
  react-day-picker: ^9.11.1
  react-dom: ^19.2.0
  react-resizable-panels: ^3.0.6
  recharts: ^3.3.0
  sonner: ^2.0.7
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.16
  turbo: ^2.5.8
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  typescript-eslint: ^8.46.2
  vaul: ^1.1.2
  vite: ^7.1.12
  vite-tsconfig-paths: ^5.1.4
  zod: ^4.1.12

catalogMode: prefer
