packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@base-ui/react': ^1.0.0
  '@eslint-react/eslint-plugin': ^2.5.0
  '@eslint/js': ^9.39.2
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/devtools-vite': ^0.4.0
  '@tanstack/eslint-plugin-query': ^5.91.2
  '@tanstack/eslint-plugin-router': ^1.141.0
  '@tanstack/react-devtools': ^0.9.0
  '@tanstack/react-form-devtools': ^0.2.10
  '@tanstack/react-form-start': ^1.27.7
  '@tanstack/react-query': ^5.90.16
  '@tanstack/react-query-devtools': ^5.91.2
  '@tanstack/react-router': ^1.144.0
  '@tanstack/react-router-devtools': ^1.144.0
  '@tanstack/react-router-ssr-query': ^1.144.0
  '@tanstack/react-start': ^1.145.3
  '@types/node': ^24.10.4
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  babel-plugin-react-compiler: ^1.0.0
  better-auth: ^1.4.10
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  date-fns: ^4.1.0
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-turbo: ^2.7.2
  husky: ^9.1.7
  lint-staged: ^16.2.7
  lucide-react: ^0.562.0
  nitro: npm:nitro-nightly@latest
  postgres: ^3.4.7
  prettier: ^3.7.4
  prettier-plugin-organize-imports: ^4.3.0
  prettier-plugin-tailwindcss: ^0.7.2
  react: ^19.2.3
  react-dom: ^19.2.3
  shadcn: ^3.6.2
  sonner: ^2.0.7
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  turbo: ^2.7.2
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  typescript-eslint: ^8.51.0
  vite: ^8.0.0-beta.5
  zod: ^4.3.3

catalogMode: prefer

overrides:
  vite: ^8.0.0-beta.5
